### PR TITLE
Namespace update to `Adapters`

### LINKED ISSUE #271: TAS_Toolkit: Namespace update from `External` to `Adapters`
#### Broken rules:

Following confirmation [here](https://github.com/BHoM/BHoM_Adapter/issues/213#issuecomment-631687011) the namespace in this toolkit, for all items except the adapter should have the namespace `BH.oM.Adapters.SomeName` or `BH.Engine.Adapters.SomeName` instead of `BH.oM.SomeName`, etc.

The Adapter namespace should remain at `BH.Adapter.SomeName` instead of `BH.Adapter.External.SomeName`.

**ALSO make sure that the default namespace is set correctly in the oM and Engine Project properties.**
➡️ [Right click on the project, navigate to the Application tab, and check the default namespace](https://user-images.githubusercontent.com/6352844/90246499-b122da00-de2c-11ea-92c0-edf0fcf81584.png).

#### Suggestions to restore compliance:

As above.

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR

 Closes #271

 

 ### Test files

@FraserGreenroyd and others to test and review as appropriate

### CODE REVIEW

File: TAS_oM/TASSettings.cs [hunk 1]
```diff
@@ -24,7 +24,7 @@
 using System.Collections.Generic;
 using BH.oM.Base;
 
-namespace BH.oM.TAS.Settings
+namespace BH.oM.Adapters.TAS
```
Comment (FraserGreenroyd) [inline TAS_oM/TASSettings.cs:27]: Please keep `Settings` in this namespace to match XML and other Environmental adapters - `BH.oM.Adapters.TAS.Settings`

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]
One minor comment, otherwise looks fine

**Review by FraserGreenroyd — APPROVED** [review]
LGTM now thanks @alelom :smile:
