### PR TITLE
TAS_Adapters Compliance fixes

### LINKED ISSUE #231: TAS_Toolkit: Compliance of adapters
There are a lot of private methods in the TASAdapers cs files.
In general for all adapters (this is a general rule that was true since the dawn of days, even before I joined, AFAIK), please consider that all efforts should be made to move methods that do not fall in CRUD or Adapter Action (Push, Pull, ...) categories in the Engine project, if they can. I believe that the only case where such methods cannot be moved would be to avoid a looping dependency (e.g. they'd need the Adapter type to work).
Additionally, starting from this Refactoring, the *Adapter.cs file should only contain the constructor, fields and properties strictly related to the Adapter.
I see there are a lot of private methods in the *Adapter.cs file that seem to possess all the qualities to make them Engine methods.

Taken from: https://github.com/BHoM/TAS_Toolkit/pull/230#pullrequestreview-344676139

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### NOTE: Depends on 

 ### Issues addressed by this PR

 Closes #231 

 
See my comment on #231

- Moved private methods from `*Adapter.cs` files to separate files, and interfaced them where appropriate.
- Refactored the adapters to use `ActionConfig` rather than private settings attributes
- any other private attributes have been handled in the action configs
- fix broken copyright headers
- change references to BHoM assemblies folders to use `$(ProgramData)`
- versioning not actually necessary 😄 

Other changes:
- Interface made for TAS documents
- Combined the three separate projects into one `TASAdapter` Project
- Input verification now all done in pull/push actions
- TASSettings object removed

 ### Test files

Test using the current TAS_Toolkit test script.

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check project-compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check copyright-compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot fix project file ref. 20261122255

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check compliance

File: TAS_Adapter/Compute/ClearCOMObject.cs [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+    public static partial class Compute
+    {
+        public static void ClearCOMObject(object obj)
+        {
+            if (obj == null) return;
+            int intrefcount;
+            do
+            {
+                intrefcount = Marshal.FinalReleaseComObject(obj);
+            } while (intrefcount > 0);
```
Comment (FraserGreenroyd) [inline TAS_Adapter/Compute/ClearCOMObject.cs]:
```suggestion
            if (obj == null)
                return;
            
            int refCount = 1;
            
            do
            {
                refCount = Marshal.FinalReleaseComObject(obj);
            }
            while (refCount > 0);
```

**Comment by Tom-Kingstone** [comment]
@BHoMBot fix project file ref. 20261504788

File: TAS_Adapter/Compute/OpenTASDocument.cs [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+using System.Threading.Tasks;
+using TCD;
+
+namespace BH.Adapter.TAS
+{
+    public static partial class Compute
+    {
+        public static ITASFile OpenTASDocument(Type type, FileSettings file)
+        {
+            if (type == typeof(T3DDocument))
```
Comment (FraserGreenroyd) [inline TAS_Adapter/Compute/OpenTASDocument.cs]: Let's put these into separate private methods similar to what you did for the `CloseTASDocument` just to keep the initial method tidy and easier to navigate if we add many more in the future.

File: TAS_Adapter/Properties/AssemblyInfo.cs [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+// You can specify all the values or you can default the Build and Revision Numbers 
+// by using the '*' as shown below:
+// [assembly: AssemblyVersion("1.0.*")]
+[assembly: AssemblyVersion("6.0.0.0")]
+[assembly: AssemblyFileVersion("6.3.0.0")]
+
+
+
+
+
```
Comment (FraserGreenroyd) [inline TAS_Adapter/Properties/AssemblyInfo.cs]:
```suggestion
```

File: TAS_Adapter/T3DAdapter/AdapterActions/Push.cs [hunk 4]
```diff
@@ -0,0 +1,76 @@
...
+            Compute.ICloseTASDocument(document, true);
+
+            return success ? objects.ToList() : new List<object>();
+        }
+    }
+}
+
+
+
+
```
Comment (FraserGreenroyd) [inline TAS_Adapter/T3DAdapter/AdapterActions/Push.cs]:
```suggestion
```

File: TAS_Adapter/T3DAdapter/CRUD/Read.cs [hunk 5]
```diff
@@ -21,26 +21,35 @@
...
         /***************************************************/
-        public virtual double DistanceTolerance { get; set; } = BH.oM.Geometry.Tolerance.Distance;
-        public virtual double PlanarTolerance { get; set; } = BH.oM.Geometry.Tolerance.Distance;
-        public virtual double MinimumSegmentLength { get; set; } = BH.oM.Geometry.Tolerance.Distance;
-        public virtual double AngleTolerance { get; set; } = BH.oM.Geometry.Tolerance.Angle;
 
-        /***************************************************/
+        protected override IEnumerable<IBHoMObject> IRead(Type type, IList indices = null, ActionConfig actionConfig = null)
+        {
+            return null;
```
Comment (FraserGreenroyd) [inline TAS_Adapter/T3DAdapter/CRUD/Read.cs]: Is this correct? I think we need to move the pull/push logic into CRUD and remove the pull/push because we're not wanting to override the pull/push per @alelom original compliance requirements for adapters.

Also blank lines at the bottom be gone please 😉

File: TAS_Adapter/T3DAdapter/TAST3DAdapter.cs [hunk 6]
```diff
@@ -23,39 +23,30 @@
...
+        public TasT3DAdapter()
         {
-            return new TASSettings
-            {
-                PlanarTolerance = planarTolerance,
-                DistanceTolerance = distanceTolerance,
-                MinimumSegmentLength = minimumSegmentLength,
-                AngleTolerance = angleTolerance,
-            };
+            BH.Engine.Base.Compute.RecordError("The TAS3D Adapter has not been fully implemented yet and cannot be used. For queries please contact the CODEOWNERS");
```
Comment (FraserGreenroyd) [inline TAS_Adapter/T3DAdapter/TAST3DAdapter.cs]: The code for pull/push of this suggests otherwise?

File: TAS_Adapter/TBDAdapter/AdapterActions/Pull.cs [hunk 7]
```diff
@@ -0,0 +1,93 @@
...
+            }
+
+            return null;
+        }
+    }
+}
+
+
+
+
```
Comment (FraserGreenroyd) [inline TAS_Adapter/TBDAdapter/AdapterActions/Pull.cs]:
```suggestion
```

File: TAS_Adapter/TBDAdapter/AdapterActions/Pull.cs [hunk 8]
```diff
@@ -0,0 +1,93 @@
...
+using BH.oM.Adapter;
+using BH.oM.Base;
+using BH.oM.Adapters.TAS;
+using BH.Engine.Adapter;
+
+namespace BH.Adapter.TAS
+{
+    public partial class TasTBDAdapter : BHoMAdapter
+    {
+        public override IEnumerable<object> Pull(IRequest request, PullType pullType = PullType.AdapterDefault, ActionConfig actionConfig = null)
```
Comment (FraserGreenroyd) [inline TAS_Adapter/TBDAdapter/AdapterActions/Pull.cs]: Let's also put this into respective CRUD methods.

File: TAS_Adapter/TBDAdapter/AdapterActions/Push.cs [hunk 9]
```diff
@@ -0,0 +1,72 @@
...
+using System.Reflection;
+using BH.oM.Adapters.TAS;
+using System.IO;
+using System.Security.AccessControl;
+
+namespace BH.Adapter.TAS
+{
+    public partial class TasTBDAdapter : BHoMAdapter
+    {
+        public override List<object> Push(IEnumerable<object> objects = null, string tag = "", PushType pushType = PushType.AdapterDefault, ActionConfig actionConfig = null)
```
Comment (FraserGreenroyd) [inline TAS_Adapter/TBDAdapter/AdapterActions/Push.cs]: Respective CRUD methods as well.

File: TAS_Adapter/TBDAdapter/CRUD/Create.cs [hunk 10]
```diff
@@ -0,0 +1,223 @@
...
+
+    /***************************************************/
+
+}
+
+
+
+
+
+
```
Comment (FraserGreenroyd) [inline TAS_Adapter/TBDAdapter/CRUD/Create.cs]:
```suggestion
```

File: TAS_Adapter/TBDAdapter/CRUD/Create.cs [hunk 11]
```diff
@@ -0,0 +1,223 @@
...
+                }
+                tbdZoneSrf.buildingElement = be;
+                //tasZoneSrf.type = BH.Engine.Adapters.TAS.Query.GetSurfaceType(element, spaces);
+                tbdZoneSrf.orientation = (float)BH.Engine.Environment.Query.Azimuth(element.BuildingElementGeometry, new BHG.Vector());
+                //tasZoneSrf.orientation = BH.Engine.Adapters.TAS.Query.GetOrientation(element.BuildingElementGeometry, bHoMSpace);
+                tbdZoneSrf.inclination = (float)BH.Engine.Environment.Query.Tilt(element.BuildingElementGeometry);
+                //tasZoneSrf.inclination = BH.Engine.Adapters.TAS.Query.GetInclination(element.BuildingElementGeometry, bHoMSpace);
+            }
+            return true;
+        */
```
Comment (FraserGreenroyd) [inline TAS_Adapter/TBDAdapter/CRUD/Create.cs]:
```suggestion
```

File: TAS_Adapter/TBDAdapter/TASTBDAdapter.cs [hunk 12]
```diff
@@ -0,0 +1,55 @@
...
+        public TasTBDAdapter()
+        {
+            m_AdapterSettings.DefaultPushType = oM.Adapter.PushType.CreateOnly;
+        }
+    }
+}
+
+
+
+
```
Comment (FraserGreenroyd) [inline TAS_Adapter/TBDAdapter/TASTBDAdapter.cs]:
```suggestion
```

File: TAS_Adapter/TSDAdapter/AdapterActions/Pull.cs [hunk 13]
```diff
@@ -0,0 +1,88 @@
...
+using BH.oM.Base;
+using BH.oM.Adapters.TAS;
+using System.IO;
+using BH.Engine.Adapter;
+
+namespace BH.Adapter.TAS
+{
+    public partial class TasTSDAdapter : BHoMAdapter
+    {
+        public override IEnumerable<object> Pull(IRequest request, PullType pullType = PullType.AdapterDefault, ActionConfig actionConfig = null)
```
Comment (FraserGreenroyd) [inline TAS_Adapter/TSDAdapter/AdapterActions/Pull.cs]: Put into CRUD.

File: TAS_Adapter/TSDAdapter/AdapterActions/Push.cs [hunk 14]
```diff
@@ -0,0 +1,43 @@
...
+
+using BH.oM.Data.Requests;
+using BH.oM.Adapter;
+using BH.oM.Base;
+
+namespace BH.Adapter.TAS
+{
+    public partial class TasTSDAdapter : BHoMAdapter
+    {
+        public override List<object> Push(IEnumerable<object> objects = null, string tag = "", PushType pushType = PushType.AdapterDefault, ActionConfig actionConfig = null)
```
Comment (FraserGreenroyd) [inline TAS_Adapter/TSDAdapter/AdapterActions/Push.cs]: Put into CRUD.

File: TAS_Adapter/TSDAdapter/CRUD/Create.cs [hunk 15]
```diff
@@ -0,0 +1,124 @@
...
+            throw new NotImplementedException();
+        }
+
+        private bool Create(BHE.Elements.InternalCondition internalCondition)
+        {
+            TSD.InternalCondition tsdInternalCondition = tsDocument.Building.AddIC(null);
+            tsdInternalCondition.name = internalCondition.Name;
+            return true; 
+        }*/
+
```
Comment (FraserGreenroyd) [inline TAS_Adapter/TSDAdapter/CRUD/Create.cs]:
```suggestion
```

File: TAS_Adapter/TSDAdapter/CRUD/Read.cs [hunk 16]
```diff
@@ -0,0 +1,190 @@
...
+            }
+
+            return buildingElementResults;      
+        }
+    }
+}
+
+
+
+
```
Comment (FraserGreenroyd) [inline TAS_Adapter/TSDAdapter/CRUD/Read.cs]:
```suggestion
```

File: TAS_Adapter/TSDAdapter/ValidateInput.cs [hunk 17]
```diff
@@ -0,0 +1,68 @@
...
+using System.Collections.Generic;
+using System.Linq;
+using System.Text;
+using System.Threading.Tasks;
+using TBD;
+using TPD;
+
+namespace BH.Adapter.TAS
+{
+    public static partial class Compute
```
Comment (FraserGreenroyd) [inline TAS_Adapter/TSDAdapter/ValidateInput.cs]: Put in a `Compute` folder

File: TAS_oM/Config/TAST3DConfig.cs [hunk 18]
```diff
@@ -0,0 +1,24 @@
...
+using System.Threading.Tasks;
+
+namespace BH.oM.Adapters.TAS
+{
+    public class TAST3DConfig : ActionConfig, ITASConfig
+    {
+        //TAST3D properties
+        public virtual FileSettings T3DFile { get; set; } = null;
+        public virtual string ProjectFolder { get; set; } = null;
+        public virtual FileSettings GBXMLFile { get; set; } = null;
```
Comment (FraserGreenroyd) [inline TAS_oM/Config/TAST3DConfig.cs]: Is this used?

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]

File: TAS_Adapter/T3DAdapter/TAST3DAdapter.cs (hunk 6 above)
Comment (Tom-Kingstone) [reply TAS_Adapter/T3DAdapter/TAST3DAdapter.cs]: When I was looking closely, the Push does not actually push any objects, and the Pull returns null anyway. Also this was how the T3D adapter was originally set up - I basically only moved it and made it compile.

File: TAS_Adapter/T3DAdapter/CRUD/Read.cs (hunk 5 above)
Comment (alelom) [reply TAS_Adapter/T3DAdapter/CRUD/Read.cs]: The implementation of CRUD (moving out the main logic from Push/Pull) can take some time and may grow the scope of this PR considerably. If so, I'd be happy with the removal of any empty override of CRUD methods (like this one), as they do not really have a reason to exist – plus raising a separate feature issue for future CRUD implementation, if required.

Comment (Tom-Kingstone) [reply TAS_Adapter/T3DAdapter/CRUD/Read.cs]: @alelom - @FraserGreenroyd and I have decided to remove the T3D Adapter and it's methods, as they don't do anything at the moment, and would likely need to be remade from scratch if it is needed in future. Therefore, the T3D Adapter is being removed.

File: TAS_oM/Config/TAST3DConfig.cs (hunk 18 above)
Comment (Tom-Kingstone) [reply TAS_oM/Config/TAST3DConfig.cs]: No, It is now gone 😃

**Comment by Tom-Kingstone** [comment]
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot fix copyright headers ref. 20264962355

**Comment by Tom-Kingstone** [comment]
> @Tom-Kingstone to confirm I have now resolved the copyright compliance and pushed a commit to this Pull Request.

I don't believe you

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check required

File: TAS_Adapter/TBDAdapter/CRUD/Read.cs [hunk 19]
```diff
@@ -0,0 +1,356 @@
...
+            }
+
+            if (config.TBDFile == null)
+            {
+                BH.Engine.Base.Compute.RecordError("You must provide a valid TBDFile FileSettings object to use this adapter.");
+                return objects;
+            }
+            else if (!File.Exists(config.TBDFile.GetFullFileName()))
+            {
+                BH.Engine.Base.Compute.RecordError("You must provide a valid existing TBD file to read from.");
```
Comment (FraserGreenroyd) [inline TAS_Adapter/TBDAdapter/CRUD/Read.cs:80]: No return here?

File: TAS_Adapter/TBDAdapter/CRUD/Read.cs [hunk 20]
```diff
@@ -0,0 +1,356 @@
...
+            }
+            return material;
+        }
+    }
+}
+
+
+
+
+
```
Comment (FraserGreenroyd) [inline TAS_Adapter/TBDAdapter/CRUD/Read.cs]:
```suggestion
```

File: TAS_Adapter/TBDAdapter/TASTBDAdapter.cs [hunk 21]
```diff
@@ -23,39 +23,29 @@
...
-        [Input("planarTolerance", "Set tolerance for planar surfaces, default is set to BH.oM.Geometry.Tolerance.Distance")]
-        [Input("angleTolerance", "The tolerance of the angle that defines a straight line. Default is set to the value defined by BH.oM.Geometry.Tolerance.Angle")]
-        [Input("minimumSegmentLength", "The length of the smallest allowed segment.Default is set to the value defined by BH.oM.Geometry.Tolerance.Distance")]
-        [Output("tasSettings", "The TAS setting to use with the TAS adapter")]
-        [ToBeRemoved("4.0", "Deprecated in favour of default create methods for settings objects.")]
-        public static TASSettings TASSettings(double planarTolerance = BH.oM.Geometry.Tolerance.Distance, double distanceTolerance = BH.oM.Geometry.Tolerance.Distance, double minimumSegmentLength = BH.oM.Geometry.Tolerance.Distance, double angleTolerance = BH.oM.Geometry.Tolerance.Angle)
+
+        [Description("Produces an TAS Adapter to allow interopability with TAS tBD files and the BHoM")]
```
Comment (FraserGreenroyd) [inline TAS_Adapter/TBDAdapter/TASTBDAdapter.cs]:
```suggestion
        [Description("Produces an TAS Adapter to allow interoperability with TAS TBD files and the BHoM")]
```

File: TAS_Adapter/TSDAdapter/CRUD/Read.cs [hunk 22]
```diff
@@ -0,0 +1,237 @@
...
+            }
+            catch (Exception ex)
+            {
+                BH.Engine.Base.Compute.RecordError($"An error occurred when reading or saving the TAS file: {ex}.");
+                Compute.ICloseTASDocument(document, false);
+                return objects;
+            }
+        }
+
+
```
Comment (FraserGreenroyd) [inline TAS_Adapter/TSDAdapter/CRUD/Read.cs:103]:
```suggestion
         /***************************************************/

```

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]

**Comment by Tom-Kingstone** [comment]
@BHoMBot check required

**Comment by Tom-Kingstone** [comment]
@BHoMBot check copyright-compliance

**Review by FraserGreenroyd — APPROVED** [review]
This looks good to me now @Tom-Kingstone thanks for picking this up 😄

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge
